dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    update: true

  sonarcloud:
    organization: "cesardl-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

git:
  depth: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.sonarscanner

before_install:
  - mysql -u travis < data/address_book_schema.sql

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn -B verify
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi

after_script:
  - export SUITE=be-core
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - export SUITE=fe-icesfaces
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - export SUITE=fe-richfaces
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage
