language: java

jdk:
  - oraclejdk8

addons:
  apt:
    update: true

cache:
  directories:
    - $HOME/.m2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean verify

after_script:
  - export SUITE=be-core
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - export SUITE=fe-icesfaces
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - export SUITE=fe-richfaces
  - export JACOCO_SOURCE_PATH=$SUITE/src/main/java
  - ./cc-test-reporter format-coverage $SUITE/target/site/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.$SUITE.json

  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage