language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

addons:
    apt:
      update: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn clean verify

after_script:
  - pwd
  - ls -lha

  - export JACOCO_SOURCE_PATH=be-core/src/main/java
  - ./cc-test-reporter format-coverage be-core/target/site/jacoco/jacoco.xml --debug --input-type jacoco
  - ./cc-test-reporter upload-coverage --debug

  - export JACOCO_SOURCE_PATH=fe-icesfaces/src/main/java
  - ./cc-test-reporter format-coverage fe-icesfaces/target/site/jacoco/jacoco.xml --debug --input-type jacoco
  - ./cc-test-reporter upload-coverage --debug

  - export JACOCO_SOURCE_PATH=fe-richfaces/src/main/java
  - ./cc-test-reporter format-coverage fe-richfaces/target/site/jacoco/jacoco.xml --debug --input-type jacoco
  - ./cc-test-reporter upload-coverage --debug